import {esc,markdown,date,kinds,button} from './workspace.js';
export function reviewPanel(r){return r?`<section class="review"><div class="review-label">需要你的审核 · ${esc(kinds[r.kind]||'作品')}</div><div class="prose">${markdown(r.question)}</div><div class="runtime-actions">${button('asset','查看审核内容',`data-id="${r.artifact_id}"`)}${button('approve','确认并继续',`data-id="${r.id}"`)}${button('reject','提出修改',`data-id="${r.id}"`)}</div><small>只确认这份作品；有意见也可以直接在对话中提出。</small></section>`:'';}
export function draftLabel(project,edit,saving){if(edit?.conflict)return '保存冲突 · 你的修改已保留';if(edit?.dirty)return saving?'正在保存…':'有未保存修改';return project.draft.revision>0?(project.draft.submitted_revision===project.draft.revision?'已保存 · 已提交导演':'已保存 · 有修改未提交'):'独立草稿 · 编辑后自动保存';}
export function draftPanel(project,edit,saving,artifact){const source=artifact(edit?.source??project.draft.source_artifact_id);return `<div class="script-pane"><div class="script-toolbar"><span class="save-state" id="save-state">${draftLabel(project,edit,saving)}</span>${button('save-script','保存草稿')}${button('submit-script','提交修改')}</div><div class="draft-context">${source?'起稿依据：'+esc(source.title):'当前项目的独立草稿'} · 保存不会改变影片</div><textarea id="script-editor" class="script-editor" aria-label="剧本编辑器" spellcheck="false">${esc(edit?.text??project.draft.text)}</textarea><div class="artifact-footnote">提交后导演会理解你的改动，再按当前授权提出方案。${edit?.conflict?button('copy-draft','复制保留我的修改'):''}</div></div>`;}
export function artifactPanel(a,snapshot,artifact){
 const adopted=snapshot.project.adopted[a.kind]===a.id,r=snapshot.reviews.find(r=>r.artifact_id===a.id&&r.status==='pending');
 const head=`<div class="artifact-meta"><span>${esc(kinds[a.kind]||a.kind)} · ${date(a.created)}</span><span class="version-badge ${adopted?'adopted':''}">${adopted?'当前采用':r?'待审核版本':'保留版本'}</span></div><h1>${esc(a.title)}</h1>`;
 const download=`<a class="button" href="/api/artifacts/${a.id}/download" download>下载${['film','trial','video','picture_master','image','audio','native_mixed'].includes(a.kind)?'原文件':'文稿'}</a>`;
 if(['film','trial','video','picture_master'].includes(a.kind))return `<div class="document">${head}<video id="film-player" data-artifact="${a.id}" class="runtime-video" src="/api/media/${a.id}" controls preload="metadata">${a.meta.vtt_path?`<track kind="subtitles" src="/api/artifacts/${a.id}/subtitles" srclang="zh" label="中文字幕" default>`:''}</video><div class="runtime-actions">${a.kind!=='picture_master'?button('annotate','标注当前时间点'):''}${download}${a.meta.subtitle_path?`<a class="button" href="/api/artifacts/${a.id}/subtitles?format=srt" download>字幕</a>`:''}${button('history','版本记录')}${['film','trial'].includes(a.kind)&&!adopted?button('adopt','从此版本继续',`data-id="${a.id}"`):''}</div><small>${a.meta.media?.duration?.toFixed(1)||'—'} 秒 · ${a.meta.picture_master_id?'已保留独立画面母版':'生成源或派生文件'} · ${esc(a.id.slice(0,8))}</small>${reviewPanel(r)}${a.meta.edit?`<details data-detail="sources-${a.id}" class="media-sources"><summary>使用的镜头与声音</summary>${[...(a.meta.edit.clips||[]),...(a.meta.edit.tracks||[])].map(c=>button('asset',esc(artifact(c.artifact_id)?.title||c.artifact_id.slice(0,8)),`data-id="${c.artifact_id}"`)).join('')}</details>`:''}</div>`;
 if(a.kind==='image')return `<div class="document">${head}<img class="runtime-image" src="/api/media/${a.id}" alt="${esc(a.title)}">${download}</div>`;
 if(['audio','native_mixed'].includes(a.kind))return `<div class="document">${head}<audio id="audio-player" data-artifact="${a.id}" controls src="/api/media/${a.id}"></audio><div class="runtime-actions">${download}</div></div>`;
 return `<div class="document">${head}${a.kind==='script'?`<div class="document-actions">${button('edit-draft','编辑草稿',`data-id="${a.id}"`)}${button('history','版本记录')}${download}</div><p class="version-hint">正在阅读这份版本的原文。手改在独立的“剧本草稿”标签中保存。</p>`:''}${(a.meta.asset_ids||[]).map(id=>artifact(id)?.kind==='image'?`<button data-action="asset" data-id="${id}"><img class="runtime-image" src="/api/media/${id}" alt="${esc(artifact(id).title)}"></button>`:'').join('')}<div class="prose document-prose">${markdown(a.text)}</div>${reviewPanel(r)}${a.kind!=='script'?download:''}</div>`;
}
export function libraryRows(snapshot,query,kind,historyKind){return [...snapshot.artifacts].reverse().filter(a=>(!kind||a.kind===kind)&&(!historyKind||a.kind===historyKind)&&(a.title+' '+a.id).toLowerCase().includes(query.toLowerCase())).map(a=>`<button class="asset-row" data-action="asset" data-id="${a.id}">${a.kind==='image'?`<img src="/api/media/${a.id}" alt="" loading="lazy">`:''}<span><strong>${esc(a.title)}</strong><small>${esc(kinds[a.kind]||a.kind)} · ${date(a.created)}${snapshot.project.adopted[a.kind]===a.id?' · 当前采用':''}</small></span><span>↗</span></button>`).join('')||'<p class="empty-artifact">没有匹配的作品。</p>';}
